SELECT ( COUNT(DISTINCT ?itemURIJ) as ?count ) 
 WHERE { 
  ?itemURIJ ca:matches ?itemURIC .
  ?itemURIJ ca:isTargetOf 
	    			[ ca:hasCoder "jhowison" ;  
	      			  ca:appliesCode citec:in_text_mention ;  
	    			 ] ;  
	  . 
	  ?itemURIC ca:isTargetOf  
					[ ca:hasCoder "cgrady" ;  
	      			  ca:appliesCode citec:in_text_mention ;  
				    ] ; 
	  . 