SELECT DISTINCT ?itemURIC
WHERE { 
  ?itemURIC bioj:matches bioj:none .
  ?itemURIC ca:isTargetOf 
	    			[ ca:hasCoder "cgrady" ;  
	      			  ca:appliesCode citec:in-text_mention ;  
	    			] ;  
	  . 
}
