SELECT DISTINCT ?itemURIJ
WHERE { 
  ?itemURIJ bioj:matches bioj:none .
  ?itemURIJ ca:isTargetOf 
	    			[ ca:hasCoder "jhowison" ;  
	      			  ca:appliesCode citec:in-text_mention ;  
	    			] ;  
	  . 
}
